# Generated by Django 2.0.2 on 2018-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('content', models.TextField()),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
