<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-03-18 21:52
=======
# Generated by Django 2.0.2 on 2018-03-09 07:26
>>>>>>> cf62b7241b864dc3801f66794b327c5c4f3a1dc8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
