# Generated by Django 2.0.2 on 2018-03-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['time']},
        ),
    ]
