# Generated by Django 2.0.2 on 2018-03-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180304_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='userName',
            new_name='user',
        ),
    ]
