# Generated by Django 2.0.2 on 2018-03-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180304_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
