# Generated by Django 2.0.2 on 2018-03-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180304_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
    ]
